export class dealDB {
    static list_order = [
        {
            "Seal No.": "#51240",
            "Shipping Bill No.": "56543",
            "Shipping Bill Date": "02/06/2021",
            "Sealing Date": "03/06/2021",
            "Sealing Time": "10.30am",
            "Port/ICD": "",
            "Loading Port": "",
            "Trailor No.":"",
            "Container No.":"",
            "Type of Seal":"",
            "Action":""
        },
        {
            "Seal No.": "#51240",
            "Shipping Bill No.": "56543",
            "Shipping Bill Date": "02/06/2021",
            "Sealing Date": "03/06/2021",
            "Sealing Time": "10.30am",
            "Port/ICD": "",
            "Loading Port": "",
            "Trailor No.":"",
            "Container No.":"",
            "Type of Seal":"",
            "Action":""
        },
        {
            "Seal No.": "#51240",
            "Shipping Bill No.": "56543",
            "Shipping Bill Date": "02/06/2021",
            "Sealing Date": "03/06/2021",
            "Sealing Time": "10.30am",
            "Port/ICD": "",
            "Loading Port": "",
            "Trailor No.":"",
            "Container No.":"",
            "Type of Seal":"",
            "Action":""
        },
        {
            "Seal No.": "#51240",
            "Shipping Bill No.": "56543",
            "Shipping Bill Date": "02/06/2021",
            "Sealing Date": "03/06/2021",
            "Sealing Time": "10.30am",
            "Port/ICD": "",
            "Loading Port": "",
            "Trailor No.":"",
            "Container No.":"",
            "Type of Seal":"",
            "Action":""
        },
        {
            "Seal No.": "#51240",
            "Shipping Bill No.": "56543",
            "Shipping Bill Date": "02/06/2021",
            "Sealing Date": "03/06/2021",
            "Sealing Time": "10.30am",
            "Port/ICD": "",
            "Loading Port": "",
            "Trailor No.":"",
            "Container No.":"",
            "Type of Seal":"",
            "Action":""
        },
        {
            "Seal No.": "#51240",
            "Shipping Bill No.": "56543",
            "Shipping Bill Date": "02/06/2021",
            "Sealing Date": "03/06/2021",
            "Sealing Time": "10.30am",
            "Port/ICD": "",
            "Loading Port": "",
            "Trailor No.":"",
            "Container No.":"",
            "Type of Seal":"",
            "Action":""
        },
        {
            "Seal No.": "#51240",
            "Shipping Bill No.": "56543",
            "Shipping Bill Date": "02/06/2021",
            "Sealing Date": "03/06/2021",
            "Sealing Time": "10.30am",
            "Port/ICD": "",
            "Loading Port": "",
            "Trailor No.":"",
            "Container No.":"",
            "Type of Seal":"",
            "Action":""
        },
        {
            "Seal No.": "#51240",
            "Shipping Bill No.": "56543",
            "Shipping Bill Date": "02/06/2021",
            "Sealing Date": "03/06/2021",
            "Sealing Time": "10.30am",
            "Port/ICD": "",
            "Loading Port": "",
            "Trailor No.":"",
            "Container No.":"",
            "Type of Seal":"",
            "Action":""
        },
        {
            "Seal No.": "#51240",
            "Shipping Bill No.": "56543",
            "Shipping Bill Date": "02/06/2021",
            "Sealing Date": "03/06/2021",
            "Sealing Time": "10.30am",
            "Port/ICD": "",
            "Loading Port": "",
            "Trailor No.":"",
            "Container No.":"",
            "Type of Seal":"",
            "Action":""
        },
        {
            "Seal No.": "#51240",
            "Shipping Bill No.": "56543",
            "Shipping Bill Date": "02/06/2021",
            "Sealing Date": "03/06/2021",
            "Sealing Time": "10.30am",
            "Port/ICD": "",
            "Loading Port": "",
            "Trailor No.":"",
            "Container No.":"",
            "Type of Seal":"",
            "Action":""
        },
        {
            "Seal No.": "#51240",
            "Shipping Bill No.": "56543",
            "Shipping Bill Date": "02/06/2021",
            "Sealing Date": "03/06/2021",
            "Sealing Time": "10.30am",
            "Port/ICD": "",
            "Loading Port": "",
            "Trailor No.":"",
            "Container No.":"",
            "Type of Seal":"",
            "Action":""
        },
    ]
}
